# ==================================================
# 파이프라인 입력 모듈 설정 파일
# ==================================================


# 사용할 YOLO 모델 파일의 전체 경로
yolo_model_path: "./models/yolo/yolo11s-pose.pt"

# 객체 탐지를 위한 신뢰도 임계값 (0.0 ~ 1.0)
# default: 기본 임계값
conf_threshold:
  default: 0.1
  person: 0.1

# YOLO 입력 이미지 사이즈
imgsz: 1280

# 탐지 및 추적을 수행할 클래스 목록
target_classes:
  - person
  # - bicycle
  # - car
  # - motorcycle
  # - bus
  # - truck
  # - dog
  # - cat

