# ==================================================
# 파이프라인 입력 모듈 설정 파일
# ==================================================

# 데이터셋 시퀀스 폴더들이 포함된 최상위 디렉토리 경로
# 예: /media/casey/DATA/my_dataset/
# dataset_base_dir: "/media/casey/Casey_Save/차량비전/178.융합센서_다중객체_추적_및_예측데이터/01.데이터/2.Validation/원천데이터/13_전방 보행자_val"

# 사용할 YOLO 모델 파일의 전체 경로
yolo_model_path: "./models/yolo/yolo11s-pose.pt"

# 객체 탐지를 위한 신뢰도 임계값 (0.0 ~ 1.0)
# default: 기본 임계값
# 클래스별로 특별한 임계값을 지정할 수 있습니다.
conf_threshold:
  default: 0.1
  person: 0.1

# YOLO 입력 이미지 사이즈
imgsz: 1280

# 탐지 및 추적을 수행할 클래스 목록
target_classes:
  - person
  # - bicycle
  # - car
  # - motorcycle
  # - bus
  # - truck
  # - dog
  # - cat

