# 전체 시스템 설정 (경로, 사용 모듈 on/off)

project_root: .

test_data_dir:
  root: tests/test_data
  images: tests/test_data/image0
  lidar: tests/test_data/lidar
  gps: tests/test_data/gps
  outputs: tests/outputs
  
  calibration:
    calib_Camera: tests/test_data/calib_Camera0.txt
    calib_LiDAR_Camera: tests/test_data/calib_CameraToLidar0.txt
    calib_LiDAR_Imu: tests/test_data/calib_LidarToImu.txt
    initial_location: tests/test_data/pos_ENU0.txt

dataset_id: 033

dataset_root:
  root: data/raw/${dataset_id}
  images: data/raw/${dataset_id}/image0
  lidar: data/raw/${dataset_id}/lidar
  gps: data/raw/${dataset_id}/gps

calibration:
  calib_Camera: data/raw/${dataset_id}/calib_Camera0.txt
  calib_LiDAR_Camera: data/raw/${dataset_id}/calib_CameraToLidar0.txt
  calib_LiDAR_Imu: data/raw/${dataset_id}/calib_LidarToImu.txt
  initial_location: data/raw/${dataset_id}/pos_ENU0.txt

bev:
  resolution: 0.01      # [m/px]
  front: 15            # [m]
  back: 0              # [m]
  left: 10              # [m]
  right: 10             # [m]
  ground_z: -1.67       # [m]